RFtest1:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: &id001
  - 0.3333333333333333
  - 0.05
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: Fiducial
  delta_prop: 1
  simulations: &id002
  - C3
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
  boost_real: true
RFtest2:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: +C2
  delta_prop: 1
  simulations:
  - C2
  - C3
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
  boost_real: true
RFtest3:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: +C2-C4
  delta_prop: 1
  simulations:
  - C2
  - C3
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
  boost_real: true
RFtest4:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: -C3-C10-C12-C15
  delta_prop: 1
  simulations:
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C11
  - C13
  - C14
  boost_real: true
RFtest5:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: -C3-C4-C5-C6
  delta_prop: 1
  simulations:
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
  boost_real: true
RFtest6:
  mode: RF
  R_type: R_corr
  agn_feedback: +delta
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback +delta
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest7:
  mode: RF
  R_type: R_corr
  agn_feedback: -delta
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback -delta
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest8:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.1
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback +0.1
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest9:
  mode: RF
  R_type: R_corr
  agn_feedback: -0.1
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback -0.1
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest10:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.2
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback +0.2
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest11:
  mode: RF
  R_type: R_corr
  agn_feedback: -0.2
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback -0.2
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest12:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.3
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback +0.3
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest13:
  mode: RF
  R_type: R_corr
  agn_feedback: -0.3
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback -0.3
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest14:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level:
  - 0.1
  - 0.1
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: noise level 0.1
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest15:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level:
  - 0.01
  - 0.01
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: noise level 0.01
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest16:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: all simulations
  delta_prop: 1
  simulations:
  - C1
  - C2
  - C3
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
  boost_real: true
RFtest17:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 1000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: leaf size 1000
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest18:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level:
  - 0.01
  - 0.01
  leaf_size: 1000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: noise 0.01+leaf 1000
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest19:
  mode: RF
  R_type: R_corr
  agn_feedback: +delta
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback +2delta
  delta_prop: 2
  simulations: *id002
  boost_real: true
RFtest20:
  mode: RF
  R_type: R_corr
  agn_feedback: -delta
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback -2delta
  delta_prop: 2
  simulations: *id002
  boost_real: true
RFtest21:
  mode: NB
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: Fiducial
  delta_prop: 1
  simulations: *id002
  boost_real: true
RFtest22:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: +C2-C12-C13-C14-C15
  delta_prop: 1
  simulations:
  - C2
  - C3
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  boost_real: true
RFtest23:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 4000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: +C2_4k
  delta_prop: 1
  simulations:
  - C2
  - C3
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
  boost_real: true
RFtest24:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: z<0.5
  delta_prop: 1
  simulations: *id002
  boost_real: true
  z:
  - 0.0
  - 0.5
RFtest25:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 4000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: +C2_4k_z<0.5
  delta_prop: 1
  simulations:
  - C2
  - C3
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
  boost_real: true
  z:
  - 0.0
  - 0.5
RFtest26:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: +C2-C13-C14-C15
  delta_prop: 1
  simulations:
  - C2
  - C3
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  boost_real: true
RFtest27:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: 0.2<z<0.9
  delta_prop: 1
  simulations: *id002
  boost_real: true
  z:
  - 0.2
  - 0.9
RFtest28:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: 0.2<z<0.8
  delta_prop: 1
  simulations: *id002
  boost_real: true
  z:
  - 0.2
  - 0.8
RFtest29:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: 0.2<z<0.7
  delta_prop: 1
  simulations: *id002
  boost_real: true
  z:
  - 0.2
  - 0.7
RFtest30:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: 0.3<z<0.5
  delta_prop: 1
  simulations: *id002
  boost_real: true
  z:
  - 0.3
  - 0.5
RFtest31:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: -C13-C14-C15
  delta_prop: 1
  simulations:
  - C3
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  boost_real: true
RFtest32:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 4000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: 4k
  delta_prop: 1
  simulations:
  - C3
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
  boost_real: true
RFtest33:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: -C12-C13-C14-C15
  delta_prop: 1
  simulations:
  - C3
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  boost_real: true
RFtest34:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: -C3
  delta_prop: 1
  simulations:
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
  boost_real: true
RFtest35:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: 0.1<z<0.35
  delta_prop: 1
  simulations: *id002
  boost_real: true
  z:
  - 0.1
  - 0.35
RFtest36:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: 0.35<z<0.80
  delta_prop: 1
  simulations: *id002
  boost_real: true
  z:
  - 0.35
  - 0.8
