RFtest1:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: &id001
  - 0.3333333333333333
  - 0.05
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: Fiducial
  simulations: &id002
  - C3
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
RFtest2:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: +C2
  simulations:
  - C2
  - C3
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
RFtest3:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: +C2-C4
  simulations:
  - C2
  - C3
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
RFtest4:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: -C3-C10-C12-C15
  simulations:
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C11
  - C13
  - C14
RFtest5:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: -C3-C4-C5-C6
  simulations:
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
RFtest6:
  mode: RF
  R_type: R_corr
  agn_feedback: +delta
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback +delta
  simulations: *id002
RFtest7:
  mode: RF
  R_type: R_corr
  agn_feedback: -delta
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback -delta
  simulations: *id002
RFtest8:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.1
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback +0.1
  simulations: *id002
RFtest9:
  mode: RF
  R_type: R_corr
  agn_feedback: -0.1
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback -0.1
  simulations: *id002
RFtest10:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.2
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback +0.2
  simulations: *id002
RFtest11:
  mode: RF
  R_type: R_corr
  agn_feedback: -0.2
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback -0.2
  simulations: *id002
RFtest12:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.3
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback +0.3
  simulations: *id002
RFtest13:
  mode: RF
  R_type: R_corr
  agn_feedback: -0.3
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: feedback -0.3
  simulations: *id002
RFtest14:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level:
  - 0.1
  - 0.1
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: noise level 0.1
  simulations: *id002
RFtest15:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level:
  - 0.01
  - 0.01
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: noise level 0.01
  simulations: *id002
RFtest16:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 10000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: all simulations
  simulations:
  - C1
  - C2
  - C3
  - C4
  - C5
  - C6
  - C7
  - C8
  - C9
  - C10
  - C11
  - C12
  - C13
  - C14
  - C15
RFtest17:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level: *id001
  leaf_size: 1000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: leaf size 1000
  simulations: *id002
RFtest18:
  mode: RF
  R_type: R_corr
  agn_feedback: 0.0
  proportional: true
  noise_level:
  - 0.01
  - 0.01
  leaf_size: 1000.0
  max_num: 10000.0
  sample_num: 100
  max_depth: 10
  exclude_outlier: false
  description: noise 0.01+leaf 1000
  simulations: *id002
